---
# tasks file for nodejs_app
- copy:
      src: "node_config.sh"
      dest: "/home/aabhusan/Desktop/"

- script:
      cmd: /home/aabhusan/Desktop/node_config.sh


- copy:
      src: "default"
      dest: "/etc/nginx/site-available/"


- service:
      name: "nginx"
      state: restarted


